// Complaint Options for each department
export const generalMedicineOptions = [
    { value: "Fever", label: "Fever" },
    { value: "Cough", label: "Cough" },
    { value: "Headache", label: "Headache" },
    { value: "Fatigue", label: "Fatigue" },
    { value: "Body Aches", label: "Body Aches" },
    { value: "Sore Throat", label: "Sore Throat" },
    { value: "Loss of Appetite", label: "Loss of Appetite" },
    { value: "Nausea", label: "Nausea" },
    { value: "Vomiting", label: "Vomiting" },
    { value: "Diarrhea", label: "Diarrhea" },
    { value: "Abdominal Pain", label: "Abdominal Pain" },
    { value: "Dizziness", label: "Dizziness" },
    { value: "Joint Pain", label: "Joint Pain" },
    { value: "Chest Pain", label: "Chest Pain" },
    { value: "Weight Loss", label: "Weight Loss" },
    { value: "Weight Gain", label: "Weight Gain" },
    { value: "Runny Nose", label: "Runny Nose" },
    { value: "Nasal Congestion", label: "Nasal Congestion" },
    { value: "Shortness of Breath", label: "Shortness of Breath" },
    { value: "General Malaise", label: "General Malaise" },
    { value: "Back Pain", label: "Back Pain" },
    { value: "Insomnia", label: "Insomnia" },
    { value: "Anxiety", label: "Anxiety" },
    { value: "Depression", label: "Depression" },
    { value: "Chills", label: "Chills" },
    { value: "Night Sweats", label: "Night Sweats" },
    { value: "Excessive Sweating", label: "Excessive Sweating" },
    { value: "Urinary Frequency", label: "Urinary Frequency" },
    { value: "Urinary Urgency", label: "Urinary Urgency" },
    { value: "Constipation", label: "Constipation" },
    { value: "Indigestion", label: "Indigestion" },
    { value: "Heartburn", label: "Heartburn" },
    { value: "Blurred Vision", label: "Blurred Vision" },
    { value: "Ear Pain", label: "Ear Pain" },
    { value: "Vertigo", label: "Vertigo" },
    { value: "Lightheadedness", label: "Lightheadedness" },
    { value: "Swollen Glands", label: "Swollen Glands" },
    { value: "Joint Stiffness", label: "Joint Stiffness" },
    { value: "Change in Bowel Habits", label: "Change in Bowel Habits" },
    { value: "Irregular Bowel Movements", label: "Irregular Bowel Movements" },
    { value: "Difficult or Painful Defecation", label: "Difficult or Painful Defecation" },
    { value: "Incomplete Evacuation", label: "Incomplete Evacuation" },
    { value: "Loose Stools", label: "Loose Stools" },
    { value: "Hard Stools", label: "Hard Stools" },
  ];
  
  export const cardiologyOptions = [
    { value: "Chest Pain", label: "Chest Pain" },
    { value: "Shortness of Breath", label: "Shortness of Breath" },
    { value: "Palpitations", label: "Palpitations" },
    { value: "Dizziness", label: "Dizziness" },
    { value: "Syncope", label: "Syncope" },
    { value: "Edema", label: "Edema" },
    { value: "High Blood Pressure", label: "High Blood Pressure" },
    { value: "Irregular Heartbeat", label: "Irregular Heartbeat" },
    { value: "Fatigue", label: "Fatigue" },
    { value: "Rapid Heart Rate", label: "Rapid Heart Rate" },
    { value: "Slow Heart Rate", label: "Slow Heart Rate" },
    { value: "Arrhythmia", label: "Arrhythmia" },
    { value: "Heart Murmur", label: "Heart Murmur" },
    { value: "Leg Pain on Exercise", label: "Leg Pain on Exercise" },
    { value: "Angina", label: "Angina" },
    { value: "Orthopnea", label: "Orthopnea" },
    { value: "Paroxysmal Nocturnal Dyspnea", label: "Paroxysmal Nocturnal Dyspnea" },
    { value: "Exertional Dyspnea", label: "Exertional Dyspnea" },
    { value: "Atrial Fibrillation", label: "Atrial Fibrillation" },
    { value: "Ventricular Tachycardia", label: "Ventricular Tachycardia" },
    { value: "Premature Ventricular Contractions", label: "Premature Ventricular Contractions" },
    { value: "Heart Failure", label: "Heart Failure" },
    { value: "Cardiomyopathy", label: "Cardiomyopathy" },
    { value: "Pericarditis", label: "Pericarditis" },
    { value: "Endocarditis", label: "Endocarditis" },
    { value: "Ischemic Heart Disease", label: "Ischemic Heart Disease" },
  ];
  
  export const gastroenterologyOptions = [
    { value: "Abdominal Pain", label: "Abdominal Pain" },
    { value: "Nausea", label: "Nausea" },
    { value: "Vomiting", label: "Vomiting" },
    { value: "Diarrhea", label: "Diarrhea" },
    { value: "Constipation", label: "Constipation" },
    { value: "Heartburn", label: "Heartburn" },
    { value: "Indigestion", label: "Indigestion" },
    { value: "Jaundice", label: "Jaundice" },
    { value: "GI Bleeding", label: "GI Bleeding" },
    { value: "Bloating", label: "Bloating" },
    { value: "Excess Gas", label: "Excess Gas" },
    { value: "Acid Reflux", label: "Acid Reflux" },
    { value: "Loss of Appetite", label: "Loss of Appetite" },
    { value: "Unexplained Weight Loss", label: "Unexplained Weight Loss" },
    { value: "Dysphagia", label: "Dysphagia" },
    { value: "Odynophagia", label: "Odynophagia" },
    { value: "Early Satiety", label: "Early Satiety" },
    { value: "Rectal Bleeding", label: "Rectal Bleeding" },
    { value: "Melena", label: "Melena" },
    { value: "Hematochezia", label: "Hematochezia" },
    { value: "Abdominal Distension", label: "Abdominal Distension" },
    { value: "Steatorrhea", label: "Steatorrhea" },
    { value: "Irritable Bowel Syndrome", label: "Irritable Bowel Syndrome" },
    { value: "Inflammatory Bowel Disease", label: "Inflammatory Bowel Disease" },
    { value: "Peptic Ulcer Disease", label: "Peptic Ulcer Disease" },
    { value: "Gallstones", label: "Gallstones" },
    { value: "Cholecystitis", label: "Cholecystitis" },
    { value: "Pancreatitis", label: "Pancreatitis" },
    { value: "Change in Bowel Habits", label: "Change in Bowel Habits" },
    { value: "Irregular Bowel Movements", label: "Irregular Bowel Movements" },
    { value: "Painful Bowel Movements", label: "Painful Bowel Movements" },
    { value: "Incomplete Evacuation", label: "Incomplete Evacuation" },
  ];
  
  export const neurologyOptions = [
    { value: "Headache", label: "Headache" },
    { value: "Seizures", label: "Seizures" },
    { value: "Dizziness", label: "Dizziness" },
    { value: "Numbness", label: "Numbness" },
    { value: "Tingling", label: "Tingling" },
    { value: "Confusion", label: "Confusion" },
    { value: "Memory Loss", label: "Memory Loss" },
    { value: "Loss of Coordination", label: "Loss of Coordination" },
    { value: "Tremors", label: "Tremors" },
    { value: "Muscle Weakness", label: "Muscle Weakness" },
    { value: "Visual Disturbances", label: "Visual Disturbances" },
    { value: "Speech Difficulties", label: "Speech Difficulties" },
    { value: "Vertigo", label: "Vertigo" },
    { value: "Ataxia", label: "Ataxia" },
    { value: "Double Vision", label: "Double Vision" },
    { value: "Difficulty Swallowing", label: "Difficulty Swallowing" },
    { value: "Facial Droop", label: "Facial Droop" },
    { value: "Slurred Speech", label: "Slurred Speech" },
    { value: "Cognitive Impairment", label: "Cognitive Impairment" },
    { value: "Abnormal Gait", label: "Abnormal Gait" },
    { value: "Neuropathic Pain", label: "Neuropathic Pain" },
    { value: "Paralysis", label: "Paralysis" },
    { value: "Loss of Fine Motor Skills", label: "Loss of Fine Motor Skills" },
    { value: "Impaired Reflexes", label: "Impaired Reflexes" },
    { value: "Difficulty Concentrating", label: "Difficulty Concentrating" },
  ];
  
  export const dermatologyOptions = [
    { value: "Rash", label: "Rash" },
    { value: "Itching", label: "Itching" },
    { value: "Acne", label: "Acne" },
    { value: "Eczema", label: "Eczema" },
    { value: "Psoriasis", label: "Psoriasis" },
    { value: "Skin Lesions", label: "Skin Lesions" },
    { value: "Hives", label: "Hives" },
    { value: "Blisters", label: "Blisters" },
    { value: "Dry Skin", label: "Dry Skin" },
    { value: "Oily Skin", label: "Oily Skin" },
    { value: "Mole Changes", label: "Mole Changes" },
    { value: "Hyperpigmentation", label: "Hyperpigmentation" },
    { value: "Hypopigmentation", label: "Hypopigmentation" },
    { value: "Rosacea", label: "Rosacea" },
    { value: "Contact Dermatitis", label: "Contact Dermatitis" },
    { value: "Seborrheic Dermatitis", label: "Seborrheic Dermatitis" },
    { value: "Vitiligo", label: "Vitiligo" },
    { value: "Melasma", label: "Melasma" },
    { value: "Cellulitis", label: "Cellulitis" },
    { value: "Warts", label: "Warts" },
    { value: "Fungal Infections", label: "Fungal Infections" },
    { value: "Scabies", label: "Scabies" },
    { value: "Lichen Planus", label: "Lichen Planus" },
    { value: "Keratosis Pilaris", label: "Keratosis Pilaris" },
    { value: "Alopecia Areata", label: "Alopecia Areata" },
    { value: "Basal Cell Carcinoma", label: "Basal Cell Carcinoma" },
    { value: "Squamous Cell Carcinoma", label: "Squamous Cell Carcinoma" },
    { value: "Melanoma", label: "Melanoma" },
  ];
  
  export const gynecologyOptions = [
    { value: "Irregular Menstruation", label: "Irregular Menstruation" },
    { value: "Pelvic Pain", label: "Pelvic Pain" },
    { value: "Vaginal Discharge", label: "Vaginal Discharge" },
    { value: "Infertility Issues", label: "Infertility Issues" },
    { value: "Menopause Symptoms", label: "Menopause Symptoms" },
    { value: "Abnormal Bleeding", label: "Abnormal Bleeding" },
    { value: "Dysmenorrhea", label: "Dysmenorrhea" },
    { value: "Ovarian Cysts", label: "Ovarian Cysts" },
    { value: "Endometriosis Symptoms", label: "Endometriosis Symptoms" },
    { value: "Polycystic Ovary Syndrome (PCOS)", label: "Polycystic Ovary Syndrome (PCOS)" },
    { value: "Premenstrual Syndrome (PMS)", label: "Premenstrual Syndrome (PMS)" },
    { value: "Fibroids", label: "Fibroids" },
    { value: "Hormonal Imbalance", label: "Hormonal Imbalance" },
    { value: "Postmenopausal Bleeding", label: "Postmenopausal Bleeding" },
    { value: "Uterine Prolapse", label: "Uterine Prolapse" },
    { value: "Cervical Dysplasia", label: "Cervical Dysplasia" },
    { value: "Vulvodynia", label: "Vulvodynia" },
    { value: "Dyspareunia", label: "Dyspareunia" },
    { value: "Menorrhagia", label: "Menorrhagia" },
    { value: "Ovarian Torsion", label: "Ovarian Torsion" },
    { value: "Ectopic Pregnancy", label: "Ectopic Pregnancy" },
    { value: "Vaginal Dryness", label: "Vaginal Dryness" },
    { value: "Recurrent Miscarriages", label: "Recurrent Miscarriages" },
    { value: "Hyperandrogenism", label: "Hyperandrogenism" },
  ];
  
  export const pulmonologyOptions = [
    { value: "Shortness of Breath", label: "Shortness of Breath" },
    { value: "Cough", label: "Cough" },
    { value: "Wheezing", label: "Wheezing" },
    { value: "Chest Tightness", label: "Chest Tightness" },
    { value: "Sputum Production", label: "Sputum Production" },
    { value: "Chronic Bronchitis", label: "Chronic Bronchitis" },
    { value: "Hemoptysis", label: "Coughing up Blood" },
    { value: "Asthma", label: "Asthma" },
    { value: "COPD", label: "Chronic Obstructive Pulmonary Disease (COPD)" },
    { value: "Pneumonia", label: "Pneumonia" },
    { value: "Emphysema", label: "Emphysema" },
    { value: "Bronchiectasis", label: "Bronchiectasis" },
    { value: "Pulmonary Embolism", label: "Pulmonary Embolism" },
    { value: "Interstitial Lung Disease", label: "Interstitial Lung Disease" },
    { value: "Pulmonary Fibrosis", label: "Pulmonary Fibrosis" },
    { value: "Sleep Apnea", label: "Sleep Apnea" },
    { value: "Pleural Effusion", label: "Pleural Effusion" },
    { value: "Pleurisy", label: "Pleurisy" },
    { value: "Lung Cancer", label: "Lung Cancer" },
  ];
  
  export const rheumatologyOptions = [
    { value: "Joint Pain", label: "Joint Pain" },
    { value: "Swelling", label: "Swelling" },
    { value: "Morning Stiffness", label: "Morning Stiffness" },
    { value: "Muscle Pain", label: "Muscle Pain" },
    { value: "Fatigue", label: "Fatigue" },
    { value: "Back Pain", label: "Back Pain" },
    { value: "Limited Range of Motion", label: "Limited Range of Motion" },
    { value: "Stiffness", label: "Stiffness" },
    { value: "Joint Tenderness", label: "Joint Tenderness" },
    { value: "Joint Redness", label: "Joint Redness" },
    { value: "Joint Deformities", label: "Joint Deformities" },
    { value: "Gout Attack", label: "Gout Attack" },
    { value: "Bursitis", label: "Bursitis" },
    { value: "Tendinitis", label: "Tendinitis" },
    { value: "Rheumatoid Arthritis", label: "Rheumatoid Arthritis" },
  ];
  
  export const nephrologyOptions = [
    { value: "Edema", label: "Edema" },
    { value: "Changes in Urination", label: "Changes in Urination" },
    { value: "Blood in Urine", label: "Blood in Urine (Hematuria)" },
    { value: "Foamy Urine", label: "Foamy Urine (Possible Proteinuria)" },
    { value: "Flank Pain", label: "Back/Flank Pain" },
    { value: "Kidney Stone Pain", label: "Kidney Stone Pain (Renal Colic)" },
    { value: "Hypertension", label: "Hypertension" },
    { value: "Decreased Urine Output", label: "Decreased Urine Output (Oliguria)" },
    { value: "Increased Urine Output", label: "Increased Urine Output (Polyuria)" },
    { value: "Nocturia", label: "Nocturia (Excessive Nighttime Urination)" },
    { value: "Urinary Frequency", label: "Urinary Frequency" },
    { value: "Acute Kidney Injury", label: "Acute Kidney Injury (AKI)" },
    { value: "Chronic Kidney Disease", label: "Chronic Kidney Disease (CKD)" },
    { value: "Electrolyte Imbalance", label: "Electrolyte Imbalance" },
    { value: "Uremia", label: "Uremia (Elevated BUN/Creatinine)" },
    { value: "Nephrotic Syndrome", label: "Nephrotic Syndrome" },
    { value: "Nephritic Syndrome", label: "Nephritic Syndrome" },
    { value: "Recurrent UTIs", label: "Recurrent UTIs (Possible Pyelonephritis)" },
    { value: "Pruritus (Uremic)", label: "Pruritus (Uremic Itching)" },
    { value: "Dialysis Access Issues", label: "Dialysis Access Issues" },
    { value: "Renal Osteodystrophy", label: "Renal Osteodystrophy (Bone Pain)" },
    { value: "Renal Colic", label: "Renal Colic (Severe Flank Pain)" },
    { value: "Hypokalemia", label: "Hypokalemia (Low Potassium)" },
    { value: "Hyperkalemia", label: "Hyperkalemia (High Potassium)" },
    { value: "Hypo/Hypernatremia", label: "Sodium Imbalances (Hypo/Hypernatremia)" },
    { value: "Renal Tubular Acidosis", label: "Renal Tubular Acidosis (RTA)" },
    { value: "Proteinuria", label: "Proteinuria" },
    { value: "Acid-Base Balance Issues", label: "Acid-Base Balance Issues (Metabolic Acidosis/Alkalosis)" },
    { value: "Diabetic Nephropathy", label: "Diabetic Nephropathy" },
    { value: "Lupus Nephritis", label: "Lupus Nephritis" },
  ];
  
  
  export const hematologyOptions = [
    { value: "Fatigue", label: "Fatigue" },
    { value: "Bleeding", label: "Bleeding" },
    { value: "Bruising", label: "Bruising" },
    { value: "Anemia", label: "Anemia" },
    { value: "Frequent Infections", label: "Frequent Infections" },
    { value: "Pallor", label: "Pallor" },
    { value: "Petechiae", label: "Petechiae" },
    { value: "Easy Bruising", label: "Easy Bruising" },
    { value: "Prolonged Bleeding", label: "Prolonged Bleeding" },
    { value: "Thrombocytopenia", label: "Thrombocytopenia" },
    { value: "Leukopenia", label: "Leukopenia" },
    { value: "Leukocytosis", label: "Leukocytosis" },
    { value: "Coagulopathy", label: "Coagulopathy" },
    { value: "Hemophilia", label: "Hemophilia" },
    { value: "Sickle Cell Disease", label: "Sickle Cell Disease" },
    { value: "Polycythemia", label: "Polycythemia" },
    { value: "Purpura", label: "Purpura" },
    { value: "Lymphadenopathy", label: "Lymphadenopathy" },
  ];
  
  export const infectiousDiseasesOptions = [
    { value: "Fever", label: "Fever" },
    { value: "Chills", label: "Chills" },
    { value: "Cough", label: "Cough" },
    { value: "Sore Throat", label: "Sore Throat" },
    { value: "Body Aches", label: "Body Aches" },
    { value: "Fatigue", label: "Fatigue" },
    { value: "Diarrhea", label: "Diarrhea" },
    { value: "Rash", label: "Rash" },
    { value: "Swollen Lymph Nodes", label: "Swollen Lymph Nodes" },
    { value: "Shortness of Breath", label: "Shortness of Breath" },
    { value: "Headache", label: "Headache" },
    { value: "Nausea", label: "Nausea" },
    { value: "Vomiting", label: "Vomiting" },
    { value: "Loss of Taste/Smell", label: "Loss of Taste/Smell" },
    { value: "Runny Nose", label: "Runny Nose" },
    { value: "Nasal Congestion", label: "Nasal Congestion" },
    { value: "Sneezing", label: "Sneezing" },
    { value: "Myalgia", label: "Myalgia" },
    { value: "Malaise", label: "Malaise" },
    { value: "Conjunctivitis", label: "Conjunctivitis" },
  ];
  
  export const psychiatryOptions = [
    { value: "Anxiety", label: "Anxiety" },
    { value: "Depression", label: "Depression" },
    { value: "Insomnia", label: "Insomnia" },
    { value: "Mood Swings", label: "Mood Swings" },
    { value: "Behavioral Changes", label: "Behavioral Changes" },
    { value: "Panic Attacks", label: "Panic Attacks" },
    { value: "Obsessive Thoughts", label: "Obsessive Thoughts" },
    { value: "Social Withdrawal", label: "Social Withdrawal" },
    { value: "Suicidal Ideation", label: "Suicidal Ideation" },
    { value: "Self-Harm", label: "Self-Harm" },
    { value: "Bipolar Disorder", label: "Bipolar Disorder" },
    { value: "Mania", label: "Mania" },
    { value: "Hypomania", label: "Hypomania" },
    { value: "Delusions", label: "Delusions" },
    { value: "Hallucinations", label: "Hallucinations" },
    { value: "Paranoia", label: "Paranoia" },
    { value: "Obsessive-Compulsive Disorder", label: "Obsessive-Compulsive Disorder" },
    { value: "Post-Traumatic Stress Disorder", label: "Post-Traumatic Stress Disorder" },
    { value: "Eating Disorders", label: "Eating Disorders" },
    { value: "Substance Abuse", label: "Substance Abuse" },
    { value: "Impulsivity", label: "Impulsivity" },
    { value: "Irritability", label: "Irritability" },
  ];
  
  export const pediatricsOptions = [
    { value: "Fever", label: "Fever" },
    { value: "Cough", label: "Cough" },
    { value: "Vomiting", label: "Vomiting" },
    { value: "Diarrhea", label: "Diarrhea" },
    { value: "Rash", label: "Rash" },
    { value: "Ear Pain", label: "Ear Pain" },
    { value: "Sore Throat", label: "Sore Throat" },
    { value: "Lethargy", label: "Lethargy" },
    { value: "Poor Feeding", label: "Poor Feeding" },
    { value: "Nasal Congestion", label: "Nasal Congestion" },
    { value: "Runny Nose", label: "Runny Nose" },
    { value: "Difficulty Breathing", label: "Difficulty Breathing" },
    { value: "Wheezing", label: "Wheezing" },
    { value: "Ear Infection", label: "Ear Infection" },
    { value: "Constipation", label: "Constipation" },
    { value: "Diaper Rash", label: "Diaper Rash" },
    { value: "Irritability", label: "Irritability" },
    { value: "Poor Weight Gain", label: "Poor Weight Gain" },
    { value: "Colic", label: "Colic" },
  ];
  
  export const orthopedicsOptions = [
    { value: "Joint Pain", label: "Joint Pain" },
    { value: "Back Pain", label: "Back Pain" },
    { value: "Fractures", label: "Fractures" },
    { value: "Muscle Pain", label: "Muscle Pain" },
    { value: "Swelling", label: "Swelling" },
    { value: "Stiffness", label: "Stiffness" },
    { value: "Limited Mobility", label: "Limited Mobility" },
    { value: "Ligament Injury", label: "Ligament Injury" },
    { value: "Tendon Injury", label: "Tendon Injury" },
    { value: "Joint Instability", label: "Joint Instability" },
    { value: "Meniscus Tear", label: "Meniscus Tear" },
    { value: "Bursitis", label: "Bursitis" },
    { value: "Sprains", label: "Sprains" },
    { value: "Dislocations", label: "Dislocations" },
    { value: "Cartilage Damage", label: "Cartilage Damage" },
    { value: "Osteoarthritis", label: "Osteoarthritis" },
    { value: "Rheumatoid Arthritis", label: "Rheumatoid Arthritis" },
    { value: "Scoliosis", label: "Scoliosis" },
    { value: "Sciatica", label: "Sciatica" },
    { value: "Plantar Fasciitis", label: "Plantar Fasciitis" },
  ];
  
  export const ophthalmologyOptions = [
    { value: "Blurry Vision", label: "Blurry Vision" },
    { value: "Eye Pain", label: "Eye Pain" },
    { value: "Redness", label: "Redness" },
    { value: "Dry Eyes", label: "Dry Eyes" },
    { value: "Itching", label: "Itching" },
    { value: "Floaters", label: "Floaters" },
    { value: "Vision Loss", label: "Vision Loss" },
    { value: "Eye Discharge", label: "Eye Discharge" },
    { value: "Double Vision", label: "Double Vision" },
    { value: "Eye Strain", label: "Eye Strain" },
    { value: "Photophobia", label: "Photophobia" },
    { value: "Glare Sensitivity", label: "Glare Sensitivity" },
    { value: "Tearing", label: "Tearing" },
    { value: "Conjunctivitis", label: "Conjunctivitis" },
    { value: "Corneal Abrasion", label: "Corneal Abrasion" },
    { value: "Uveitis", label: "Uveitis" },
    { value: "Glaucoma", label: "Glaucoma" },
    { value: "Cataract", label: "Cataract" },
    { value: "Color Vision Deficiency", label: "Color Vision Deficiency" },
    { value: "Night Blindness", label: "Night Blindness" },
    { value: "Eye Floaters and Spots", label: "Eye Floaters and Spots" },
  ];
  
  export const otolaryngologyOptions = [
    { value: "Ear Pain", label: "Ear Pain" },
    { value: "Hearing Loss", label: "Hearing Loss" },
    { value: "Sore Throat", label: "Sore Throat" },
    { value: "Sinus Pain", label: "Sinus Pain" },
    { value: "Nasal Congestion", label: "Nasal Congestion" },
    { value: "Tinnitus", label: "Tinnitus" },
    { value: "Vertigo", label: "Vertigo" },
    { value: "Ear Infection", label: "Ear Infection" },
    { value: "Otitis Media", label: "Otitis Media" },
    { value: "Otitis Externa", label: "Otitis Externa" },
    { value: "Eustachian Tube Dysfunction", label: "Eustachian Tube Dysfunction" },
    { value: "Nasal Polyps", label: "Nasal Polyps" },
    { value: "Deviated Septum", label: "Deviated Septum" },
    { value: "Loss of Smell", label: "Loss of Smell" },
    { value: "Hoarseness", label: "Hoarseness" },
    { value: "Laryngitis", label: "Laryngitis" },
    { value: "Pharyngitis", label: "Pharyngitis" },
    { value: "Dysphagia", label: "Difficulty Swallowing" },
  ];
  
  export const urologyOptions = [
    { value: "Urinary Frequency", label: "Urinary Frequency" },
    { value: "Urinary Urgency", label: "Urinary Urgency" },
    { value: "Painful Urination", label: "Painful Urination" },
    { value: "Hematuria", label: "Hematuria" },
    { value: "Incontinence", label: "Incontinence" },
    { value: "Urinary Retention", label: "Urinary Retention" },
    { value: "Nocturia", label: "Nocturia" },
    { value: "Urinary Hesitancy", label: "Urinary Hesitancy" },
    { value: "Dysuria", label: "Dysuria" },
    { value: "Recurrent UTIs", label: "Recurrent UTIs" },
    { value: "Bladder Pain", label: "Bladder Pain" },
    { value: "Interstitial Cystitis", label: "Interstitial Cystitis" },
    { value: "Prostate Enlargement", label: "Prostate Enlargement" },
    { value: "Erectile Dysfunction", label: "Erectile Dysfunction" },
    { value: "Weak Urinary Stream", label: "Weak Urinary Stream" },
    { value: "Urinary Dribbling", label: "Urinary Dribbling" },
  ];
  
  export const oncologyOptions = [
    { value: "Unexplained Weight Loss", label: "Unexplained Weight Loss" },
    { value: "Fatigue", label: "Fatigue" },
    { value: "Pain", label: "Pain" },
    { value: "Lumps", label: "Lumps" },
    { value: "Changes in Skin", label: "Changes in Skin" },
    { value: "Persistent Cough", label: "Persistent Cough" },
    { value: "Difficulty Swallowing", label: "Difficulty Swallowing" },
    { value: "Abnormal Bleeding", label: "Abnormal Bleeding" },
    { value: "Blood in Urine", label: "Blood in Urine" },
    { value: "Blood in Stool", label: "Blood in Stool" },
    { value: "Night Sweats", label: "Night Sweats" },
    { value: "Chronic Hoarseness", label: "Chronic Hoarseness" },
    { value: "Change in Bowel Habits", label: "Change in Bowel Habits" },
    { value: "Lymph Node Enlargement", label: "Lymph Node Enlargement" },
    { value: "Bone Pain", label: "Bone Pain" },
    { value: "Abdominal Pain", label: "Abdominal Pain" },
  ];
  
  export const endocrinologyOptionsExpanded = [
    { value: "Fatigue", label: "Fatigue" },
    { value: "Weight Changes", label: "Weight Changes" },
    { value: "Excessive Thirst", label: "Excessive Thirst" },
    { value: "Frequent Urination", label: "Frequent Urination" },
    { value: "Heat Intolerance", label: "Heat Intolerance" },
    { value: "Cold Intolerance", label: "Cold Intolerance" },
    { value: "Hair Loss", label: "Hair Loss" },
    { value: "Excessive Sweating", label: "Excessive Sweating" },
    { value: "Irregular Menstrual Cycle", label: "Irregular Menstrual Cycle" },
    { value: "Hypothyroidism", label: "Hypothyroidism" },
    { value: "Hyperthyroidism", label: "Hyperthyroidism" },
    { value: "Goiter", label: "Goiter" },
    { value: "Cushing's Syndrome", label: "Cushing's Syndrome" },
    { value: "Addison's Disease", label: "Addison's Disease" },
    { value: "Acromegaly", label: "Acromegaly" },
    { value: "Amenorrhea", label: "Amenorrhea" },
    { value: "Hirsutism", label: "Hirsutism" },
    { value: "Infertility", label: "Infertility" },
    { value: "Delayed Puberty", label: "Delayed Puberty" },
    { value: "Osteoporosis", label: "Osteoporosis" },
    { value: "Impaired Glucose Tolerance", label: "Impaired Glucose Tolerance" },
    { value: "Hyperglycemia", label: "Hyperglycemia" },
    { value: "Hypoglycemia", label: "Hypoglycemia" },
  ];
  
  // Mapping: Department -> Complaint Options
  export const complaintOptionsByDepartment = {
    "General Medicine": generalMedicineOptions,
    "Cardiology": cardiologyOptions,
    "Gastroenterology": gastroenterologyOptions,
    "Neurology": neurologyOptions,
    "Dermatology": dermatologyOptions,
    "Gynecology": gynecologyOptions,
    "Pulmonology": pulmonologyOptions,
    "Rheumatology": rheumatologyOptions,
    "Nephrology": nephrologyOptions,
    "Hematology": hematologyOptions,
    "Infectious Diseases": infectiousDiseasesOptions,
    "Psychiatry": psychiatryOptions,
    "Pediatrics": pediatricsOptions,
    "Orthopedics": orthopedicsOptions,
    "Ophthalmology": ophthalmologyOptions,
    "Otolaryngology": otolaryngologyOptions,
    "Urology": urologyOptions,
    "Oncology": oncologyOptions,
    "Endocrinology": endocrinologyOptionsExpanded,
  };
  
  export const frequencySuggestions = [
    "Once a day",
    "Twice a day",
    "Thrice a day",
    "Four times a day",
    "Five times a day",
    "Six times a day",
    "Seven times a day",
    "Every day",
    "Every other day",
    "Alternate days",
    "On-demand",
    "As needed",
    "Frequent",
    "Intermittent",
    "Occasionally",
    "2 times/day",
    "2 times a day",
    "2x per day",
    "3 times/day",
    "3 times a day",
    "3x per day",
    "4 times/day",
    "4 times a day",
    "4x per day",
    "5 times/day",
    "5 times a day",
    "5x per day",
    "6 times/day",
    "6 times a day",
    "6x per day",
    "7 times/day",
    "7 times a day",
    "7x per day",
    "Once daily",
    "Twice daily",
    "Thrice daily",
    "Every 8 hours",
    "Every 12 hours",
    "Every 6 hours",
    "Every 4 hours",
    "Every 2 hours",
    "Every 30 minutes",
    "Continuous infusion",
    "In cycles",
    "Bedtime",
    "Before meals",
    "After meals",
    "Before bedtime",
    "Postprandial",
    "Preprandial",
    "Morning",
    "Afternoon",
    "Evening",
    "Night",
    "Weekly",
    "Biweekly",
    "Monthly",
    "Yearly",
    // Common medical abbreviations:
    "OD (once daily)",
    "BD (twice daily)",
    "TDS (thrice daily)",
    "QID (4 times daily)",
    "PRN (as needed)",
    // Hour-based frequencies:
    "q12h (every 12 hours)",
    "q8h (every 8 hours)",
    "q6h (every 6 hours)",
    "q4h (every 4 hours)",
    "q2h (every 2 hours)",
    // Some mixed numeric text examples:
    "2-3 times/day",
    "3-4 times/week",
    "Every 2 days",
    "Every 3 days",
  ];  
  
  export const severitySuggestions = [
    "Mild",
    "Moderate",
    "Severe",
    "Very Severe",
  ];
  
  export const durationSuggestions = [
    "1 day",
    "2 days",
    "3 days",
    "4 days",
    "5 days",
    "6 days",
    "1 week",
    "2 weeks",
    "3 weeks",
    "4 weeks",
    "1 month",
    "2 months",
    "3 months",
    "6 months",
    "1 year",
    "Acute",
    "Subacute",
    "Chronic",
    "Intermittent",
    "Continuous",
    "Short term",
    "Long term"
  ];
  

  export const pastHistorySuggestions = [
    "Mild hyperlipidemia",
    "Severe hyperlipidemia",
    "Fever (low-grade)",
    "High fever",
    "Hypertension",
    "High blood pressure",
    "Diabetes Mellitus Type 1",
    "Diabetes Mellitus Type 2",
    "Asthma",
    "Chronic Obstructive Pulmonary Disease (COPD)",
    "Bronchitis",
    "Pneumonia",
    "Gastroesophageal Reflux Disease (GERD)",
    "Peptic Ulcer Disease",
    "Hepatitis B",
    "Hepatitis C",
    "Liver Cirrhosis",
    "Fatty Liver Disease",
    "Chronic Kidney Disease",
    "Renal Failure",
    "Urinary Tract Infection",
    "Thyroid Disorder",
    "Hypothyroidism",
    "Hyperthyroidism",
    "Rheumatoid Arthritis",
    "Osteoarthritis",
    "Osteoporosis",
    "Anemia",
    "Iron Deficiency Anemia",
    "Sickle Cell Disease",
    "Hemophilia",
    "Stroke",
    "Transient Ischemic Attack (TIA)",
    "Heart Failure",
    "Coronary Artery Disease",
    "Previous Myocardial Infarction",
    "Angina",
    "Arrhythmia",
    "Atrial Fibrillation",
    "Valvular Heart Disease",
    "Peripheral Vascular Disease",
    "Cancer (Breast, Lung, Colon, Prostate, etc.)",
    "Migraine",
    "Cluster Headaches",
    "Epilepsy",
    "Seizure Disorder",
    "Multiple Sclerosis",
    "Parkinson's Disease",
    "Alzheimer's Disease",
    "Dementia",
    "Depression",
    "Anxiety Disorder",
    "Bipolar Disorder",
    "Schizophrenia",
    "Chronic Pain Syndrome",
    "Fibromyalgia",
    "Inflammatory Bowel Disease (Crohn's Disease, Ulcerative Colitis)",
    "Irritable Bowel Syndrome (IBS)",
    "Chronic Pancreatitis",
    "Gallstones",
    "Viral Infections (e.g., COVID-19, Influenza)",
    "Tuberculosis",
    "Sexually Transmitted Infections",
    "Deep Vein Thrombosis (DVT)",
    "Pulmonary Embolism",
    "Autoimmune Diseases (e.g., Lupus, Sjögren's Syndrome)",
    "Connective Tissue Disorder",
    "Hemodialysis",
    "Bone Fractures",
    "Previous Surgeries (Appendectomy, Cholecystectomy, Hysterectomy, Prostatectomy, Mastectomy)",
    "Traumatic Brain Injury",
    "Sports Injuries",
    "Drug Allergies",
    "Food Allergies",
    "Seasonal Allergies",
    "Obesity",
    "Polycystic Ovary Syndrome (PCOS)",
    "Celiac Disease",
    "Diverticulitis",
    "Appendicitis",
    "Chronic Sinusitis",
    "History of Radiation Therapy",
    "History of Chemotherapy",
    "History of Immunosuppressant Use",
    "2 days of altered bowel habits",
    "1 week of constipation",
    "3 days of watery stools",
    "Intermittent constipation for 2 months",
    "Occasional loose stools",
    "Gradual change in bowel habits",
    "Sudden onset of diarrhea",
    "Episodic abdominal cramping and diarrhea",
    "Chronic constipation",
    "Frequent urge to defecate",
  ];
  
  export const personalHistorySuggestions = [
    "Non-smoker",
    "Smoker",
    "Former smoker",
    "Occasional smoker",
    "Heavy smoker",
    "Alcohol use",
    "Heavy alcohol use",
    "Moderate alcohol use",
    "Occasional alcohol use",
    "No alcohol",
    "Vegetarian",
    "Non-vegetarian",
    "Vegan",
    "Pescatarian",
    "Gluten-free diet",
    "Keto diet",
    "Regular exercise",
    "Sedentary lifestyle",
    "History of drug abuse",
    "Substance abuse",
    "Recreational drug use",
    "High stress",
    "Low stress",
    "Poor sleep",
    "Adequate sleep",
    "Insomnia",
    "Shift worker",
    "Night shift worker",
    "Irregular work schedule",
    "Regular medication use",
    "Over-the-counter medication use",
    "Herbal supplements",
    "High caffeine intake",
    "Low caffeine intake",
    "Social drinker",
    "Non-social drinker",
    "Marijuana use",
    "Intermittent fasting",
    "High sugar diet",
    "Processed food consumption",
    "Excessive screen time",
    "Regular meditation",
    "Regular yoga",
    "Frequent travel",
    "Exposure to environmental toxins",
    "Excessive fast food consumption",
    "High salt diet",
    "Low salt diet",
    "Caffeine dependence",
    "Frequent energy drink consumption",
    "History of overeating",
    "History of under-eating",
    "Mindful eating",
    "Adherence to Mediterranean diet",
    "Regular self-care",
    "Stress management practices",
    "Balanced lifestyle",
    "2 days of altered bowel habits",
    "1 week of constipation",
    "3 days of watery stools",
    "Intermittent constipation for 2 months",
    "Occasional loose stools",
    "Gradual change in bowel habits",
    "Sudden onset of diarrhea",
    "Episodic abdominal cramping and diarrhea",
    "Chronic constipation",
    "Frequent urge to defecate",
  ];
  
  export const familyHistorySuggestions = [
    "Diabetes",
    "Hypertension",
    "Heart Disease",
    "Cancer (various types)",
    "Stroke",
    "Genetic Disorders",
    "Autoimmune Diseases",
    "Chronic Kidney Disease",
    "Osteoporosis",
    "Asthma",
    "Allergies",
    "Mental Illness",
    "Depression",
    "Anxiety",
    "High Cholesterol",
    "Obesity",
    "Alzheimer's Disease",
    "Parkinson's Disease",
    "Multiple Sclerosis",
    "Bipolar Disorder",
    "Schizophrenia",
    "Substance Abuse",
    "Liver Disease",
    "Thyroid Disorders",
    "Glaucoma",
    "Macular Degeneration",
    "Sickle Cell Disease",
    "Hemophilia",
    "Rheumatoid Arthritis",
    "Osteoarthritis",
    "Colon Cancer",
    "Breast Cancer",
    "Prostate Cancer",
    "Ovarian Cancer",
    "Endometrial Cancer",
    "Pancreatic Cancer",
    "Cerebral Aneurysm",
    "Atrial Fibrillation",
    "Familial Hypercholesterolemia",
    "Inherited Arrhythmias",
    "Congenital Heart Defects",
    "Familial Mediterranean Fever",
    "Celiac Disease",
    "Crohn's Disease",
    "Ulcerative Colitis",
    "Psoriasis",
    "Eczema",
    "Migraine",
    "Epilepsy",
    "Huntington's Disease",
    "Amyotrophic Lateral Sclerosis (ALS)",
    "Polycystic Ovary Syndrome (PCOS)",
    "Ankylosing Spondylitis",
  ];


  export const allergySuggestions = [
    // Common Drug Allergies
    "Penicillin",
    "Cephalosporins",
    "Sulfa Drugs (e.g., Sulfonamides)",
    "Aspirin",
    "NSAIDs (e.g., Ibuprofen)",
    "Codeine",
    "Morphine",
    "Latex",
    "Local Anesthetics (e.g., Novocaine)",
    "Tetracycline",
    "Gentamicin",
    "Vancomycin",
    "Contrast Dye (Iodine-based)",
    "Insulin (Animal-sourced)",
    "ACE Inhibitors (e.g., Enalapril)",
    "Beta-Blockers (e.g., Propranolol)",
    "Chemotherapy Agents (Various)",
    "Heparin",
    "Vaccines (Various Components)",
    "Anticonvulsants (e.g., Phenytoin)",
    "Opioids (e.g., Hydrocodone)",
    "Bacitracin",
    "Neomycin",
  
    // Common Food Allergies
    "Dairy Products",
    "Peanuts",
    "Tree Nuts (Almonds, Walnuts, Cashews, etc.)",
    "Cow's Milk",
    "Eggs",
    "Fish (e.g., Cod, Salmon, Tuna)",
    "Shellfish (Shrimp, Crab, Lobster, etc.)",
    "Wheat",
    "Soy",
    "Sesame",
    "Seeds (Sunflower, Pumpkin, etc.)",
    "Coconut",
    "Chocolate",
    "Citrus Fruits (Oranges, Lemons, etc.)",
    "Strawberries",
    "Bananas",
    "Kiwi",
    "Mustard",
    "Celery",
    "Corn",
    "Tomatoes",
    "Garlic",
    "Onions",
    "Yeast",
    "Gluten (Wheat, Barley, Rye)",
  
    // Environmental Allergies
    "Pollen (Tree, Grass, Weed)",
    "Dust Mites",
    "Pet Dander (Cats, Dogs)",
    "Mold Spores",
    "Ragweed",
    "Bee Stings",
    "Wasp Stings",
    "Hornet Stings",
    "Cockroach Droppings",
    "Feathers",
    "Nickel",
    "Cosmetics (Various Fragrances/Preservatives)",
    "Poison Ivy",
    "Poison Oak",
    "Poison Sumac",
    "Detergents (Household Cleaners)",
    "Fabric Softeners",
    "Soaps",
    "Perfumes/Fragrances",
    "Scented Lotions",
    "Sunscreens",
    "Hair Dyes",
    "Nail Polish",
    "Henna",
  
    // Less Common Food & Environmental
    "Eggplant",
    "Avocado",
    "Mushrooms",
    "Sesame Oil",
    "Spices (e.g., Cinnamon, Turmeric)",
    "Artificial Food Coloring (e.g., Tartrazine)",
    "Preservatives (e.g., Sulfites)",
    "Monosodium Glutamate (MSG)",
    "Paprika",
    "Pumpkin",
    "Peas",
    "Lentils",
    "Apple",
    "Peach",
    "Grapes",
    "Gelatin",
    "Barley",
    "Rye",
    "Tree Pollen (Birch, Oak, Pine)",
    "Grass Pollen (Timothy, Bermuda)",
    "Weed Pollen (Nettle, Plantain)",
    "Animal Dander (Rabbits, Hamsters)",
    "Insect Venom (Fire Ants, Yellow Jackets)",
    "Cleaning Solvents",
    "Adhesive Bandages (Glue)",
  ];

  export const medicationHistorySuggestions = [
    // ANTIDIABETICS
    "Metformin (500 mg, 850 mg, 1000 mg)",
    "Sulfonylureas (Glibenclamide, Glipizide, Glimepiride)",
    "DPP-4 Inhibitors (Sitagliptin, Linagliptin)",
    "GLP-1 Agonists (Liraglutide, Semaglutide)",
    "SGLT2 Inhibitors (Empagliflozin, Dapagliflozin)",
    "Thiazolidinediones (Pioglitazone, Rosiglitazone)",
    "Insulin (Regular, NPH, Basal, Rapid-acting, etc.)",
    "Vildagliptin",
    "Acarbose",
  
    // LIPID-LOWERING AGENTS
    "Atorvastatin (10 mg, 20 mg, 40 mg)",
    "Rosuvastatin (5 mg, 10 mg, 20 mg)",
    "Simvastatin (10 mg, 20 mg, 40 mg)",
    "Pravastatin",
    "Ezetimibe",
    "Fenofibrate",
    "Gemfibrozil",
  
    // ANTIHYPERTENSIVES
    "Lisinopril (5 mg, 10 mg)",
    "Enalapril",
    "Ramipril",
    "Losartan",
    "Valsartan",
    "Telmisartan",
    "Irbesartan",
    "Amlodipine",
    "Nifedipine (Extended Release)",
    "Diltiazem",
    "Verapamil",
    "Hydrochlorothiazide (HCTZ)",
    "Chlorthalidone",
    "Spironolactone",
    "Eplerenone",
    "Metoprolol (Tartrate, Succinate)",
    "Propranolol",
    "Bisoprolol",
    "Carvedilol",
    "Clonidine",
    "Methyldopa",
  
    // ANALGESICS / ANTI-INFLAMMATORY
    "Paracetamol (Acetaminophen)",
    "Ibuprofen",
    "Naproxen",
    "Diclofenac",
    "Ketorolac",
    "Aspirin (75 mg, 81 mg, 325 mg)",
    "Celecoxib",
    "Meloxicam",
    "Indomethacin",
    "Tramadol",
    "Morphine (IR, SR)",
    "Fentanyl (patch, IV)",
    "Oxycodone",
    "Hydrocodone",
    "Codeine",
    "Tapentadol",
  
    // ANTIPLATELETS & ANTICOAGULANTS
    "Clopidogrel",
    "Ticagrelor",
    "Prasugrel",
    "Warfarin",
    "Heparin (Unfractionated)",
    "Low-Molecular-Weight Heparin (Enoxaparin)",
    "Dabigatran",
    "Rivaroxaban",
    "Apixaban",
    "Edoxaban",
  
    // GASTROINTESTINAL
    "Omeprazole",
    "Esomeprazole",
    "Pantoprazole",
    "Lansoprazole",
    "Rabeprazole",
    "Ranitidine",
    "Famotidine",
    "Antacids (Aluminum Hydroxide/Magnesium Hydroxide)",
    "Sucralfate",
    "Domperidone",
    "Metoclopramide",
    "Ondansetron",
    "Mesalamine (5-ASA)",
    "Sulfasalazine",
    "Lactulose",
  
    // ANTI-INFECTIVES
    // (Antibiotics)
    "Amoxicillin",
    "Amoxicillin-Clavulanate",
    "Cephalexin",
    "Ceftriaxone",
    "Cefuroxime",
    "Cefixime",
    "Vancomycin",
    "Linezolid",
    "Clindamycin",
    "Azithromycin",
    "Clarithromycin",
    "Metronidazole",
    "Piperacillin-Tazobactam",
    "Meropenem",
    "Imipenem",
    "Gentamicin",
    "Amikacin",
    "Ciprofloxacin",
    "Levofloxacin",
    "Trimethoprim-Sulfamethoxazole (Co-trimoxazole)",
    "Nitrofurantoin",
    // (Antifungals)
    "Fluconazole",
    "Itraconazole",
    "Voriconazole",
    "Amphotericin B",
    "Nystatin",
    // (Antivirals)
    "Acyclovir",
    "Valacyclovir",
    "Oseltamivir",
    "Tenofovir",
    "Lamivudine",
    "Efavirenz",
    // (Antihelminthics)
    "Albendazole",
    "Mebendazole",
    "Ivermectin",
  
    // RESPIRATORY
    "Salbutamol (Albuterol) Inhaler",
    "Salmeterol + Fluticasone (Combination Inhaler)",
    "Budesonide Inhaler",
    "Tiotropium (Spiriva)",
    "Montelukast",
    "Theophylline",
    "Prednisone",
    "Prednisolone",
  
    // THYROID & HORMONES
    "Levothyroxine",
    "Liothyronine",
    "Propylthiouracil (PTU)",
    "Methimazole (Carbimazole)",
    "Oral Contraceptives (Combined Pill)",
    "Progesterone (Various Forms)",
    "Estrogen (HRT)",
    "Testosterone Replacement",
  
    // NEURO / PSYCHIATRY
    "Carbamazepine",
    "Valproic Acid (Sodium Valproate)",
    "Phenytoin",
    "Lamotrigine",
    "Topiramate",
    "Levetiracetam (Keppra)",
    "Gabapentin",
    "Pregabalin",
    "Diazepam",
    "Lorazepam",
    "Alprazolam",
    "Clonazepam",
    "Zolpidem",
    "SSRIs (Sertraline, Fluoxetine, Paroxetine, Citalopram, Escitalopram)",
    "SNRIs (Venlafaxine, Duloxetine)",
    "TCAs (Amitriptyline, Nortriptyline)",
    "Bupropion",
    "Trazodone",
    "Lithium",
    "Risperidone",
    "Olanzapine",
    "Quetiapine",
    "Aripiprazole",
    "Haloperidol",
    "Clozapine",
    "Methylphenidate",
    "Modafinil",
  
    // RHEUMATOLOGY / IMMUNOSUPPRESSANTS
    "Methotrexate",
    "Hydroxychloroquine",
    "Sulfasalazine",
    "Leflunomide",
    "Azathioprine",
    "Mycophenolate Mofetil",
    "Cyclosporine",
    "Tacrolimus",
    "Adalimumab",
    "Etanercept",
    "Infliximab",
    "Rituximab",
  
    // HORMONAL / GONADAL
    "Clomiphene Citrate",
    "Tamoxifen",
    "Anastrozole",
    "Leuprolide",
  
    // DERMATOLOGICAL
    "Isotretinoin",
    "Hydroxyzine",
    "Topical Steroids (Hydrocortisone, Clobetasol)",
    "Tacrolimus Ointment (Topical)",
    "Calamine Lotion",
  
    // MISCELLANEOUS
    "Levocetirizine",
    "Fexofenadine",
    "Cetirizine",
    "Betahistine",
    "Prochlorperazine",
    "Sodium Bicarbonate",
    "Vitamin D3 (Cholecalciferol)",
    "Calcium Supplements",
    "B-Complex Vitamins",
    "Folic Acid",
    "Iron Supplements",
    "Potassium Chloride",
    "Magnesium Supplements",
    "Tranexamic Acid",
    "Desmopressin (DDAVP)",
    "Baclofen",
    "Sildenafil",
    "Tadalafil",
    "Duloxetine (for diabetic neuropathy)",
    "Allopurinol",
    "Febuxostat",
    "Colchicine",
    "Probenecid",
  
    // ONCOLOGY (Chemotherapeutics)
    "Methotrexate (High Dose in Oncology)",
    "Cyclophosphamide",
    "Doxorubicin (Adriamycin)",
    "Cisplatin",
    "Carboplatin",
    "5-Fluorouracil (5-FU)",
    "Capecitabine",
    "Paclitaxel",
    "Docetaxel",
    "Bevacizumab",
    "Imatinib",
    "Tamoxifen (Breast Cancer)",
    "Anastrozole (Aromatase Inhibitor)",
    "Letrozole",
    "Leuprolide (Prostate Cancer)",
    "Bicalutamide",
  ];
  
  
  export const surgicalHistorySuggestions = [
    // GENERAL & ABDOMINAL SURGERIES
    "Appendectomy",
    "Cholecystectomy",
    "Hernia Repair (Inguinal, Umbilical, Incisional)",
    "Exploratory Laparotomy",
    "Bowel Resection (Colectomy, Small Bowel Resection)",
    "Gastrectomy (Partial/Total)",
    "Splenectomy",
    "Pancreatectomy (Partial/Total)",
    "Whipple Procedure (Pancreaticoduodenectomy)",
    "Adrenalectomy",
    "Lap Band",
    "Gastric Bypass (Roux-en-Y)",
    "Sleeve Gastrectomy",
    "Hiatal Hernia Repair",
    "Liver Resection (Hepatectomy)",
    "Appendicolith Removal",
  
    // OBSTETRIC & GYNECOLOGICAL SURGERIES
    "C-Section (Cesarean Section)",
    "Hysterectomy (Total/Partial)",
    "Myomectomy (Fibroid Removal)",
    "Oophorectomy (Ovary Removal)",
    "Salpingectomy (Fallopian Tube Removal)",
    "Tubal Ligation",
    "Ectopic Pregnancy Surgery",
    "Endometrial Ablation",
    "Pelvic Organ Prolapse Repair",
    "Laparoscopic Ovarian Cystectomy",
    "D&C (Dilation and Curettage)",
  
    // ORTHOPEDIC SURGERIES
    "Knee Replacement (Total/Partial)",
    "Hip Replacement (Total/Partial)",
    "Shoulder Replacement",
    "ACL Reconstruction",
    "Meniscectomy or Meniscus Repair",
    "Rotator Cuff Repair",
    "Carpal Tunnel Release",
    "Spinal Fusion (Lumbar/Cervical)",
    "Laminectomy",
    "Discectomy",
    "Arthroscopic Joint Surgery (Knee, Shoulder, etc.)",
    "Tendon Repair (Achilles, Biceps, etc.)",
    "Open Reduction and Internal Fixation (ORIF) of Fractures",
    "External Fixation of Fractures",
  
    // CARDIOTHORACIC SURGERIES
    "CABG (Coronary Artery Bypass Graft)",
    "Angioplasty (with or without Stent)",
    "Valve Replacement/Repair (Aortic, Mitral, etc.)",
    "Heart Transplant",
    "Pacemaker or ICD Implantation",
    "VATS (Video-Assisted Thoracoscopic Surgery)",
    "Lobectomy or Pneumonectomy (Lung Resection)",
    "Thoracotomy",
    "Esophagectomy",
    "Repair of Aortic Aneurysm (AAA Repair)",
    "Mediastinoscopy",
    
    // ENT (EAR, NOSE, THROAT) SURGERIES
    "Tonsillectomy",
    "Adenoidectomy",
    "Tympanoplasty",
    "Mastoidectomy",
    "Stapedectomy",
    "Cochlear Implant Surgery",
    "Functional Endoscopic Sinus Surgery (FESS)",
    "Septoplasty",
    "Rhinoplasty (Medical/Functional)",
    "Thyroidectomy",
    "Parathyroidectomy",
    "Salivary Gland Excision (Parotidectomy, Submandibulectomy)",
  
    // OPHTHALMOLOGIC SURGERIES
    "Cataract Surgery",
    "LASIK (Laser-Assisted In Situ Keratomileusis)",
    "PRK (Photorefractive Keratectomy)",
    "Vitrectomy",
    "Glaucoma Surgery (Trabeculectomy)",
    "Retinal Detachment Repair",
    "Corneal Transplant",
    "Strabismus Surgery",
  
    // UROLOGY & NEPHROLOGY SURGERIES
    "TURP (Transurethral Resection of Prostate)",
    "Nephrectomy (Kidney Removal)",
    "Kidney Transplant",
    "Ureteric Stent Placement",
    "Cystectomy (Partial/Total)",
    "Prostatectomy (Radical or Partial)",
    "Urethroplasty",
    "Varicocele Repair",
    "Bladder Sling Procedure",
    "Pyeloplasty",
    
    // NEUROSURGERIES
    "Craniotomy (Tumor Resection, Clot Evacuation)",
    "Spinal Decompression (Laminectomy, Laminotomy)",
    "Microdiscectomy",
    "VP Shunt Placement (Ventriculoperitoneal Shunt)",
    "Aneurysm Clipping or Coiling",
    "Epilepsy Surgery",
    "Pituitary Tumor Resection (Transsphenoidal)",
    "Chiari Decompression",
  
    // ONCOLOGIC SURGERIES
    "Mastectomy (Simple, Radical, Modified)",
    "Lumpectomy (Breast-Conserving Surgery)",
    "Colon Resection for Colon Cancer",
    "Prostatectomy for Prostate Cancer",
    "Nephrectomy for Renal Cancer",
    "WLE (Wide Local Excision) for Skin Cancer",
    "Lymph Node Dissection",
    "Thyroid Lobectomy for Thyroid Cancer",
    "Hepatic Resection for Liver Metastases",
    "Pancreaticoduodenectomy (Whipple) for Pancreatic Cancer",
    
    // PLASTIC & RECONSTRUCTIVE SURGERIES
    "Skin Graft (Split-Thickness/Full-Thickness)",
    "Breast Reconstruction (Implant/Flap)",
    "Abdominoplasty (Tummy Tuck)",
    "Liposuction",
    "Facelift (Rhytidectomy)",
    "Blepharoplasty (Eyelid Surgery)",
    "Burn Reconstruction",
    "Cleft Lip/Palate Repair",
    
    // VASCULAR SURGERIES
    "Carotid Endarterectomy",
    "AV Fistula Creation for Dialysis",
    "Peripheral Bypass Surgery (Fem-Pop Bypass)",
    "Varicose Vein Stripping/Endovenous Ablation",
    "Endovascular Aneurysm Repair (EVAR)",
    
    // OTHERS / MISC
    "Dental Extractions/Wisdom Tooth Removal",
    "Oral/Maxillofacial Surgery (Jaw Reconstruction)",
    "Lymph Node Biopsy/Excision",
    "Bone Marrow Biopsy (Surgical)",
    "Minor Skin Excisions (Lipoma, Cyst, etc.)",
    "Penile Prosthesis Implant",
    "Testicular Torsion Surgery",
    "Carpal Tunnel Release",
    "Trigger Finger Release",
  ];  

  
  // A comprehensive list of major cities in India for the City select dropdown
  export const cityOptions = [
    { value: "Mumbai", label: "Mumbai" },
    { value: "Delhi", label: "Delhi" },
    { value: "Bengaluru", label: "Bengaluru" },
    { value: "Hyderabad", label: "Hyderabad" },
    { value: "Ahmedabad", label: "Ahmedabad" },
    { value: "Chennai", label: "Chennai" },
    { value: "Kolkata", label: "Kolkata" },
    { value: "Pune", label: "Pune" },
    { value: "Jaipur", label: "Jaipur" },
    { value: "Lucknow", label: "Lucknow" },
    { value: "Kanpur", label: "Kanpur" },
    { value: "Nagpur", label: "Nagpur" },
    { value: "Visakhapatnam", label: "Visakhapatnam" },
    { value: "Indore", label: "Indore" },
    { value: "Thane", label: "Thane" },
    { value: "Bhopal", label: "Bhopal" },
    { value: "Patna", label: "Patna" },
    { value: "Vadodara", label: "Vadodara" },
    { value: "Ghaziabad", label: "Ghaziabad" },
    { value: "Ludhiana", label: "Ludhiana" },
    { value: "Agra", label: "Agra" },
    { value: "Nashik", label: "Nashik" },
    { value: "Faridabad", label: "Faridabad" },
    { value: "Meerut", label: "Meerut" },
    { value: "Rajkot", label: "Rajkot" },
    { value: "Kalyan-Dombivli", label: "Kalyan-Dombivli" },
    { value: "Vasai-Virar", label: "Vasai-Virar" },
    { value: "Varanasi", label: "Varanasi" },
    { value: "Srinagar", label: "Srinagar" },
    { value: "Aurangabad", label: "Aurangabad" },
    { value: "Dhanbad", label: "Dhanbad" },
    { value: "Amritsar", label: "Amritsar" },
    { value: "Navi Mumbai", label: "Navi Mumbai" },
    { value: "Allahabad", label: "Allahabad" },
    { value: "Ranchi", label: "Ranchi" },
    { value: "Howrah", label: "Howrah" },
    { value: "Coimbatore", label: "Coimbatore" },
    { value: "Jabalpur", label: "Jabalpur" },
    { value: "Gwalior", label: "Gwalior" },
    { value: "Vijayawada", label: "Vijayawada" },
    { value: "Jodhpur", label: "Jodhpur" },
    { value: "Madurai", label: "Madurai" },
    { value: "Raipur", label: "Raipur" },
    { value: "Kota", label: "Kota" },
    { value: "Chandigarh", label: "Chandigarh" },
    { value: "Guwahati", label: "Guwahati" },
    { value: "Solapur", label: "Solapur" },
    { value: "Hubli-Dharwad", label: "Hubli-Dharwad" },
    { value: "Mysore", label: "Mysore" },
    { value: "Tiruchirappalli", label: "Tiruchirappalli" },
    { value: "Bareilly", label: "Bareilly" },
    { value: "Aligarh", label: "Aligarh" },
    { value: "Tiruppur", label: "Tiruppur" },
    { value: "Moradabad", label: "Moradabad" },
    { value: "Jalandhar", label: "Jalandhar" },
    { value: "Bhubaneswar", label: "Bhubaneswar" },
    { value: "Salem", label: "Salem" },
    { value: "Warangal", label: "Warangal" },
    { value: "Guntur", label: "Guntur" },
    { value: "Thiruvananthapuram", label: "Thiruvananthapuram" },
    { value: "Gorakhpur", label: "Gorakhpur" },
    { value: "Jamshedpur", label: "Jamshedpur" },
    { value: "Bhiwandi", label: "Bhiwandi" },
    { value: "Saharanpur", label: "Saharanpur" },
    { value: "Dehradun", label: "Dehradun" },
    { value: "Nanded", label: "Nanded" },
    { value: "Rajahmundry", label: "Rajahmundry" },
    { value: "Jammu", label: "Jammu" },
    { value: "Siliguri", label: "Siliguri" },
    { value: "Udaipur", label: "Udaipur" },
    { value: "Kolhapur", label: "Kolhapur" },
    { value: "Akola", label: "Akola" },
    { value: "Amravati", label: "Amravati" },
    { value: "Bhilai", label: "Bhilai" },
    { value: "Sangli", label: "Sangli" },
    { value: "Miraj", label: "Miraj" },
    { value: "Mangalore", label: "Mangalore" },
    { value: "Tirunelveli", label: "Tirunelveli" },
    { value: "Ujjain", label: "Ujjain" },
    { value: "Cuttack", label: "Cuttack" },
    { value: "Firozabad", label: "Firozabad" },
    { value: "Jhansi", label: "Jhansi" },
    { value: "Ulhasnagar", label: "Ulhasnagar" },
    { value: "Durgapur", label: "Durgapur" },
    { value: "Asansol", label: "Asansol" },
    { value: "Bhavnagar", label: "Bhavnagar" },
    { value: "Kurnool", label: "Kurnool" },
    { value: "Kollam", label: "Kollam" },
    { value: "Nizamabad", label: "Nizamabad" },
    { value: "Erode", label: "Erode" },
    { value: "Bhagalpur", label: "Bhagalpur" },
    { value: "Kakinada", label: "Kakinada" },
    { value: "Tirupati", label: "Tirupati" },
    { value: "Darbhanga", label: "Darbhanga" },
    { value: "Muzaffarpur", label: "Muzaffarpur" },
    { value: "Gaya", label: "Gaya" },
    { value: "Panipat", label: "Panipat" },
    { value: "Bardhaman", label: "Bardhaman" },
    { value: "Bathinda", label: "Bathinda" },
    { value: "Rohtak", label: "Rohtak" },
    { value: "Bilaspur", label: "Bilaspur" },
    { value: "Sambalpur", label: "Sambalpur" },
    { value: "Muzaffarnagar", label: "Muzaffarnagar" },
    { value: "Etawah", label: "Etawah" },
    { value: "Bulandshahr", label: "Bulandshahr" },
    { value: "Rampur", label: "Rampur" },
    { value: "Hapur", label: "Hapur" },
    { value: "Bikaner", label: "Bikaner" },
    { value: "Ajmer", label: "Ajmer" },
    { value: "Bhilwara", label: "Bhilwara" },
    { value: "Bharatpur", label: "Bharatpur" },
    { value: "Hisar", label: "Hisar" },
    { value: "Karnal", label: "Karnal" },
    { value: "Ambala", label: "Ambala" },
    { value: "Roorkee", label: "Roorkee" },
    { value: "Rourkela", label: "Rourkela" },
    { value: "Silchar", label: "Silchar" },
    { value: "Dibrugarh", label: "Dibrugarh" },
    { value: "Tinsukia", label: "Tinsukia" },
    { value: "Kharagpur", label: "Kharagpur" },
    { value: "Balasore", label: "Balasore" },
    { value: "Berhampur", label: "Berhampur" },
    { value: "Haldia", label: "Haldia" },
    { value: "Ambikapur", label: "Ambikapur" },
    { value: "Bhind", label: "Bhind" },
    { value: "Chhapra", label: "Chhapra" },
    { value: "Gulbarga", label: "Gulbarga" },
    { value: "Ichalkaranji", label: "Ichalkaranji" },
    { value: "Korba", label: "Korba" },
    { value: "Mahbubnagar", label: "Mahbubnagar" },
    { value: "Mirzapur", label: "Mirzapur" },
    { value: "Nagercoil", label: "Nagercoil" },
    { value: "Ongole", label: "Ongole" },
    { value: "Puducherry", label: "Puducherry" },
    { value: "Rajpur", label: "Rajpur" },
    { value: "Sikar", label: "Sikar" },
    { value: "Sonipat", label: "Sonipat" },
    { value: "Yamunanagar", label: "Yamunanagar" },
    { value: "Bundi", label: "Bundi" },
    { value: "Chittorgarh", label: "Chittorgarh" },
    { value: "Pali", label: "Pali" },
    { value: "Nagaur", label: "Nagaur" },
    { value: "Hanumangarh", label: "Hanumangarh" },
    { value: "Sri Ganganagar", label: "Sri Ganganagar" },
    { value: "Churu", label: "Churu" },
    { value: "Jhunjhunu", label: "Jhunjhunu" },
    { value: "Jhalawar", label: "Jhalawar" },
    { value: "Barmer", label: "Barmer" },
    { value: "Dhaulpur", label: "Dhaulpur" },
    { value: "Banswara", label: "Banswara" },
  ];
  


// constants.js

// Complaints Suggestions (multi)
export const complaintSuggestions = [
  "Fever",
  "Cough",
  "Headache",
  "Sore Throat",
  "Fatigue",
  "Vomiting",
];

// Diagnosis Suggestions (multi)
export const diagnosisSuggestions = [
  "Pneumonia",
  "Migraine",
  "COVID-19",
  "Hypertension",
  "Diabetes Mellitus",
  "Acute Bronchitis",
  "Malaria",
];

// Tests Suggestions (multi)
export const testSuggestions = [
  "Blood Culture",
  "Chest X-ray",
  "CBC",
  "ECG",
  "MRI Brain",
  "Blood Sugar (Fasting)",
  "Liver Function Test",
];


// This array has "value" keys only (no label)
export const TU = [
  { value: "Oral-To be swallowed" },
  { value: "Place on tongue" },
  { value: "Oral-self dissolving" },
  { value: "Topical Application" },
  { value: "Transdermal/On Skin" },
  { value: "Intravenous (IV)" },
  { value: "Intramuscular (IM)" },
  { value: "Subcutaneous (SC)" },
  { value: "Intraarterial" },
  { value: "Nasal application" },
  { value: "Inhalation" },
  { value: "Vaginal Application" },
  { value: "Into Bone" },
  { value: "Eye Application" },
  { value: "Ear Application" },
  { value: "Rectal Application" }
];


export const whenSuggestions = [
  "Before Food", "After Food", "Before Breakfast", "After Breakfast",
  "Before Lunch", "After Lunch", "SoS", "Empty Stomach", "Morning-evening",
  "Before Dinner", "After Dinner", "With Tea", "Before Sleep", "Bed Time", ""
];

export const unitSuggestions = [
  "mg", "mcg", "ml", "iu", "drops", "gm", "tsp", "units", "tab", "cap", "puffs", "vial"
];

// Dosage Suggestions (single)
export const dosageSuggestions = [
  "1 - 0 - 0",
  "0 - 0 - 1",
  "1 - 0 - 1",
  "1 - 1 - 1",
  "1 - 1 - 0",
  "0 - 1 - 0",
  "0 - 1 - 1",
  "1 - 1 - 1 - 1",
  "1 - 1 - 1 - 0",
  "1 - 1 - 0 - 1",
  "1 - 0 - 1 - 1",
  "0 - 1 - 1 - 1",
  "1 - 1 - 0 - 0",
  "1 - 0 - 0 - 0",
  "0 - 0 - 0 - 1",
  "0 - 0 - 1 - 0",
  "0 - 1 - 0 - 0",
  "0 - 1 - 1 - 0",
  "1 - 1 - 0 - 0",
  "1 - 0 - 1 - 0",
  "1 - 0 - 0 - 1",
  "0 - 0 - 1 - 1",
];

// Timing Suggestions (single)
export const timingSuggestions = [
  "OD (once daily)",
  "BD (twice daily)",
  "TID (thrice daily)",
  "QID (4 times daily)",
  "HS (at bedtime)",
];